### ISSUE TITLE
Keyboard input does not work on boot

### ISSUE THREAD

**Issue by Tyilo** [anatol/booster#80] opened 2021-04-13 11:44 UTC
When using `mkinitcpio` with the `sd-encrypt` hook, the dm-crypt password prompt shows asterisks by default, whereas booster doesn't show anything at all.

Given that my keyboard recently stopped working in booster (probably due to https://github.com/systemd/systemd/issues/19191), it would be nice if it was possible to enable showing asterisks when entering the password in booster.

Maybe this can already be done by loading `sd-encrypt` somehow?

**Comment by anatol** [comment] 2021-04-13 20:21
> Maybe this can already be done by loading sd-encrypt somehow?

Booster does not use mkinitcpio hook and neither uses any systemd functionality.

> Given that my keyboard recently stopped working in booster

It is weird. If the problem in booster exists then it should be debugged. Do you still see this problem with the latest booster? I'll be happy to debug and fix it properly.

>  it would be nice if it was possible to enable showing asterisks when entering the password in booster.

Visible asterisks reduce security of the password as it shows how many symbols it contains. But I am fine with having this feature optional e.g. enabling it with <TAB> pressed.

**Comment by Tyilo** [comment] 2021-04-15 13:12
> It is weird. If the problem in booster exists then it should be debugged. Do you still see this problem with the latest booster? I'll be happy to debug and fix it properly.

I think this might be caused by the systemd bug. I will re-test booster when it is fixed.

> Visible asterisks reduce security of the password as it shows how many symbols it contains. But I am fine with having this feature optional e.g. enabling it with `TAB` pressed.

Yeah that sounds great.

**Comment by anatol** [comment] 2021-04-15 19:57
It turns out that the recent changes to `linux` package [1] break booster keyboard functionality. I am working on a fix for it.


[1] https://github.com/archlinux/svntogit-packages/commit/f0db16ba5ecc6bd683033d9f42a1bd1442c72071#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a

**Comment by anatol** [comment] 2021-04-15 20:22
And it is strange, I just rebuilt image for the latest kernel and it works just fine. The `atkbd` and `serio` modules included as expected.

It must be some glich similar to #54.

**Comment by anatol** [comment] 2021-04-16 00:31
So I boot into the old kernel:

```
$ uname -r
5.11.12-arch1-1
```

This kernel has builtin `serio` and `atkdb` modules. In the next kernel version these modules got shipped as loadable *.ko files and it should be added to the output image.

`booster` handles such case (implemented in #54). It gets information about loadable modules from `/sys/modules`. So I checked this `sys` listing at `5.11.12-arch1-1` and it is what I have:

```
$ ls /sys/module 
8250              cpuidle              gpiolib_acpi           iwlwifi        printk                    snd_hwdep                     thunderbolt
8250_dw           cqhci                haltpoll               jbd2           processor                 snd_intel_dspcfg              tpm
ac97_bus          crc16                hid                    joydev         processor_thermal_device  snd_pcm                       tpm_crb
acpi              crc32c_intel         i2c_algo_bit           kernel         processor_thermal_mbox    snd_pcm_dmaengine             tpm_tis
acpi_pad          crc32_pclmul         i2c_i801               keyboard       processor_thermal_rapl    snd_soc_acpi                  tpm_tis_core
acpiphp           crc_t10dif           i2c_smbus              kvm            processor_thermal_rfim    snd_soc_acpi_intel_match      trusted
acpi_thermal_rel  crct10dif_pclmul     i8042                  kvm_intel      psmouse                   snd_soc_core                  typec
aesni_intel       cryptd               i915                   ledtrig_audio  pstore                    snd_soc_hdac_hda              typec_ucsi
af_alg            cryptomgr            idma64                 libahci        random                    snd_soc_skl                   ucsi_acpi
agpgart           crypto_simd          int3400_thermal        libarc4        rapl                      snd_soc_sst_dsp               uhci_hcd
ahci              crypto_user          int3403_thermal        libata         rcupdate                  snd_soc_sst_ipc               usbcore
algif_hash        device_hmem          int340x_thermal_zone   libnvdimm      rcutree                   snd_sof                       uvcvideo
algif_skcipher    dm_crypt             intel_cstate           mac80211       rfcomm                    snd_sof_intel_byt             vfat
apparmor          dm_mod               intel_gtt              mac_hid        rfkill                    snd_sof_intel_hda             video
battery           drm                  intel_idle             mbcache        rmi_core                  snd_sof_intel_hda_common      videobuf2_common
blk_cgroup        drm_kms_helper       intel_lpss             mc             rmi_smbus                 snd_sof_intel_ipc             videobuf2_memops
blk_crypto        dynamic_debug        intel_lpss_pci         mei            rng_core                  snd_sof_pci                   videobuf2_v4l2
block             e1000e               intel_pch_thermal      mei_hdcp       rtc_cmos                  snd_sof_xtensa_dsp            videobuf2_vmalloc
bluetooth         ecc                  intel_pmc_bxt          mei_me         scsi_mod                  snd_timer                     videodev
bnep              ecdh_generic         intel_pmc_core         mmc_core       sdhci                     soundcore                     vt
bpf_preload       edac_core            intel_powerclamp       module         sdhci_pci                 soundwire_bus                 watchdog
btbcm             ee1004               intel_rapl_common      mousedev       serio_raw                 soundwire_cadence             wmi
btintel           efi_pstore           intel_rapl_msr         msr            sg                        soundwire_generic_allocation  wmi_bmof
btrtl             ehci_hcd             intel_soc_dts_iosf     netpoll        shpchp                    soundwire_intel               workqueue
btusb             encrypted_keys       intel_uncore           nls_iso8859_1  slab_common               spurious                      x86_pkg_temp_thermal
button            ext4                 intel_wmi_thunderbolt  nmi_backtrace  snd                       srcutree                      xen
cbc               fat                  ip6table_filter        nvme           snd_compress              suspend                       xhci_hcd
ccm               fb                   ip6_tables             nvme_core      snd_hda_codec             syscopyarea                   xhci_pci
cec               fb_sys_fops          ip_tables              page_alloc     snd_hda_codec_conexant    sysfillrect                   xhci_pci_renesas
cfg80211          firmware_class       ipv6                   pcie_aspm      snd_hda_codec_generic     sysimgblt                     x_tables
cmac              fscrypto             irqbypass              pciehp         snd_hda_codec_hdmi        sysrq                         xt_comment
configfs          fuse                 iTCO_vendor_support    pci_hotplug    snd_hda_core              tcp_cubic                     xz_dec
coretemp          ghash_clmulni_intel  iTCO_wdt               pcspkr         snd_hda_ext_core          thermal                       zswap
cpufreq           glue_helper          iwlmvm                 pnp            snd_hda_intel             thinkpad_acpi
```

neither `serio` nor `atkbd` is not listed under this sysfs. This is super weird. Does anybody have an idea why it is not here? And what is the best way to get the complete list of builtin modules for the currently running kernel?

**Comment by anatol** [comment] 2021-04-16 00:41
And as a workaround for the original keyboard problem either

1. use `universal` mode
2. add `modules: serio,atkbd` to the config

**Comment by anatol** [comment] 2021-09-24 20:22
@Tyilo have you had this problem recently? Should the ticket be closed as obsolete?

**Comment by Tyilo** [comment] 2021-09-24 20:27
Yes, I thin this is not a problem anymore.

**Comment by bjo81** [comment] 2021-09-29 12:20
I switched to booster and my usb-keyboard is not working, so no clue if this was caused by this bug.

**Comment by anatol** [comment] 2021-09-29 17:07
@bjo81 could you please provide more information about your setup? what booster version do you use? is there any special about your keyboard (bluetooth??).

Could you please also provide output of `lsmod` and `booster -debug`?

**Comment by bjo81** [comment] 2021-09-29 17:20
Sure. I'm using now "modules_force_load: hid_cherry". 

lsmod:
```Module                  Size  Used by
rpcsec_gss_krb5        36864  0
auth_rpcgss           159744  1 rpcsec_gss_krb5
nfsv4                 929792  2
dns_resolver           16384  1 nfsv4
nfs                   434176  2 nfsv4
lockd                 126976  1 nfs
grace                  16384  1 lockd
fscache               405504  1 nfs
netfs                  53248  1 fscache
cmac                   16384  2
algif_hash             16384  1
algif_skcipher         16384  1
af_alg                 32768  6 algif_hash,algif_skcipher
bnep                   28672  2
btusb                  69632  0
btrtl                  28672  1 btusb
btbcm                  20480  1 btusb
btintel                32768  1 btusb
bluetooth             729088  28 btrtl,btintel,btbcm,bnep,btusb
ecdh_generic           16384  1 bluetooth
ecc                    40960  1 ecdh_generic
mousedev               24576  0
joydev                 28672  0
crc16                  16384  1 bluetooth
qrtr                   20480  4
ns                     36864  1 qrtr
intel_rapl_msr         20480  0
intel_rapl_common      28672  1 intel_rapl_msr
snd_hda_codec_realtek   159744  1
amdgpu               7802880  4
snd_hda_codec_generic    98304  1 snd_hda_codec_realtek
edac_mce_amd           36864  0
hwmon_vid              16384  0
ledtrig_audio          16384  1 snd_hda_codec_generic
snd_hda_codec_hdmi     73728  1
eeepc_wmi              16384  0
gpu_sched              49152  1 amdgpu
asus_wmi               45056  1 eeepc_wmi
snd_hda_intel          57344  0
i2c_algo_bit           16384  1 amdgpu
drm_ttm_helper         16384  1 amdgpu
sunrpc                663552  12 nfsv4,auth_rpcgss,lockd,rpcsec_gss_krb5,nfs
snd_intel_dspcfg       28672  1 snd_hda_intel
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
sparse_keymap          16384  1 asus_wmi
snd_hda_codec         176128  4 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek
ttm                    86016  2 amdgpu,drm_ttm_helper
rfkill                 32768  4 asus_wmi,bluetooth
video                  57344  1 asus_wmi
snd_hda_core          110592  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek
wmi_bmof               16384  0
kvm                  1056768  0
drm_kms_helper        303104  1 amdgpu
snd_hwdep              16384  1 snd_hda_codec
irqbypass              16384  1 kvm
snd_pcm               151552  4 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_core
vfat                   24576  2
lzo_rle                16384  12
fat                    86016  1 vfat
cec                    73728  1 drm_kms_helper
pcspkr                 16384  0
rapl                   16384  0
snd_timer              45056  1 snd_pcm
agpgart                45056  1 ttm
sp5100_tco             20480  0
syscopyarea            16384  1 drm_kms_helper
snd                   114688  8 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_pcm
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
ccp                   118784  0
k10temp                16384  0
fb_sys_fops            16384  1 drm_kms_helper
soundcore              16384  1 snd
i2c_piix4              28672  0
wmi                    36864  2 asus_wmi,wmi_bmof
gpio_amdpt             20480  0
gpio_generic           20480  1 gpio_amdpt
mac_hid                16384  0
pinctrl_amd            32768  0
acpi_cpufreq           32768  0
vboxnetflt             32768  0
vboxnetadp             28672  0
vboxdrv               528384  2 vboxnetadp,vboxnetflt
sg                     40960  0
crypto_user            20480  0
acpi_call              16384  0
drm                   589824  8 gpu_sched,drm_kms_helper,amdgpu,drm_ttm_helper,ttm
fuse                  167936  3
zram                   36864  2
bpf_preload            16384  0
ip_tables              32768  0
x_tables               53248  1 ip_tables
xfs                  2068480  1
libcrc32c              16384  1 xfs
usbhid                 65536  0
dm_crypt               57344  1
encrypted_keys         24576  1 dm_crypt
trusted                40960  2 encrypted_keys,dm_crypt
tpm                    90112  1 trusted
dm_mod                167936  3 dm_crypt
tee                    36864  1 trusted
rng_core               16384  2 ccp,tpm
asn1_encoder           16384  1 trusted
cbc                    16384  0
aesni_intel           380928  5
crypto_simd            16384  1 aesni_intel
ghash_clmulni_intel    16384  0
cryptd                 28672  4 crypto_simd,ghash_clmulni_intel
crc32_pclmul           16384  0
crc32c_intel           24576  1
crct10dif_pclmul       16384  1
r8169                  98304  0
realtek                36864  1
mdio_devres            16384  1 r8169
libphy                159744  3 r8169,mdio_devres,realtek
xhci_pci               20480  0
xhci_pci_renesas       20480  1 xhci_pci
hid_cherry             16384  0
```
booster -debug:
```
active host modules: [encrypted_keys thermal efi_pstore r8169 snd_hda_codec_generic cpuidle cryptomgr syscopyarea dns_resolver spurious ccp edac_core gpu_sched acpi_call mdio_devres battery vt libahci tcp_cubic nmi_backtrace irqbypass xhci_hcd xen 8250 video btrtl cryptd kfence shpchp ecdh_generic crypto_simd soundcore srcutree ecc rcupdate crypto_user random rtc_cmos zram dm_crypt snd_hda_codec_hdmi pinctrl_amd haltpoll snd_hwdep drm_kms_helper sysimgblt hwmon_vid device_hmem pstore sysrq acpi_cpufreq tee snd_intel_sdw_acpi libphy processor scsi_mod kernel page_alloc algif_hash snd_hda_intel crc16 mousedev realtek grace usbhid ahci pciehp pci_hotplug gpiolib_acpi i2c_algo_bit nfsv4 xhci_pci_renesas nvme trusted mac_hid ns snd_hda_codec snd_hda_codec_realtek auth_rpcgss dynamic_debug intel_rapl_msr intel_idle libcrc32c keyboard zswap agpgart bpf_preload cmac algif_skcipher netfs memory_hotplug snd_timer ledtrig_audio fb page_reporting k10temp hid netpoll apparmor usbcore sparse_keymap snd_intel_dspcfg ghash_clmulni_intel blk_cgroup nvme_core pcie_aspm pnp secretmem vboxnetadp libnvdimm rfkill btintel joydev af_alg asus_wmi lzo_rle cpufreq ehci_hcd lockd ipv6 sunrpc bluetooth intel_pmc_core slab_common wmi_bmof suspend vboxnetflt btbcm crc_t10dif fuse amdgpu acpiphp vboxdrv fb_sys_fops bnep configfs sp5100_tco btusb cec asn1_encoder x_tables blk_crypto edac_mce_amd xhci_pci rcutree xfs drm_ttm_helper sysfillrect button kvm cbc aesni_intel block hid_cherry qrtr crct10dif_pclmul snd_pcm xz_dec rapl snd fscache dm_mod crc32c_intel libata sg ip_tables ttm module snd_hda_core intel_rapl_common msr eeepc_wmi gpio_amdpt i2c_piix4 firmware_class wmi acpi clocksource fscrypto rpcsec_gss_krb5 rng_core uhci_hcd crc32_pclmul printk pcspkr vfat gpio_generic watchdog nfs workqueue tpm fat drm]
activate module configfs
activate module netfs
activate module grace
activate module xfs
activate module fscache
activate module fat
activate module nfs
activate module lockd
activate module fuse
activate module vfat
activate module pstore
activate module nfsv4
activate module crct10dif_pclmul
activate module ghash_clmulni_intel
activate module aesni_intel
activate module crc32_pclmul
activate module crc32c_intel
activate module lzo_rle
activate module cbc
activate module cryptomgr
activate module af_alg
activate module cmac
activate module algif_hash
activate module cryptd
activate module crypto_simd
activate module algif_skcipher
activate module ecc
activate module ecdh_generic
activate module crypto_user
activate module r8169
activate module dm_mod
activate module dm_crypt
activate module tpm
activate module uhci_hcd
activate module xhci_hcd
activate module ehci_hcd
activate module xhci_pci_renesas
activate module xhci_pci
activate module usbhid
activate module ahci
softdep: unable to resolve module name aead2
softdep: unable to resolve module name nls
softdep: unable to resolve module name platform:gpio_keys_polled
softdep: unable to resolve module name vfio_iommu_spapr_tce
module xhci_pci depends on firmware renesas_usb_fw.mem but the firmware file does not exist
no matches found for a device alias 'acpi:LNXSYBUS:'
no matches found for a device alias 'usb:v0A12p0001d8891dcE0dsc01dp01icE0isc01ip01in01'
no matches found for a device alias 'input:b0003v046Ap0023e0111-e0,1,2,3,4,k71,72,73,74,77,78,80,82,83,85,86,87,88,89,8A,8B,8C,8E,8F,90,94,95,96,98,9B,9C,9E,9F,A1,A3,A4,A5,A6,A7,A8,A9,AB,AC,AD,AE,B0,B1,B2,B5,B6,CA,CE,CF,D0,D1,D2,D4,D8,D9,DB,DF,E0,E1,E4,E5,E6,E7,E8,E9,EA,EB,F0,F1,F4,100,161,162,166,16A,16E,172,174,176,177,178,179,17A,17B,17C,17D,17F,180,182,183,185,188,189,18C,18D,18E,18F,190,191,192,193,195,197,198,199,19A,19C,1A0,1A1,1A2,1A3,1A4,1A5,1A6,1A7,1A8,1A9,1AA,1AB,1AC,1AD,1AE,1AF,1B0,1B1,1B7,1BA,240,241,242,243,244,245,246,247,248,249,250,251,260,261,262,263,264,265,r6,C,a20,m4,lsfw'
no matches found for a device alias 'platform:reg-dummy'
no matches found for a device alias 'platform:vboxdrv'
no matches found for a device alias 'input:b0019v0000p0001e0000-e0,1,k74,ramlsfw'
no matches found for a device alias 'acpi:PNP0501:'
no matches found for a device alias 'pci:v00001022d00001453sv00001043sd00008747bc06sc04i00'
no matches found for a device alias 'pci:v00001022d00001463sv00000000sd00000000bc06sc00i00'
no matches found for a device alias 'pci:v00001022d00001464sv00000000sd00000000bc06sc00i00'
no matches found for a device alias 'pci:v00001022d00001467sv00000000sd00000000bc06sc00i00'
no matches found for a device alias 'acpi:LNXCPU:'
no matches found for a device alias 'scsi:t-0x00'
no matches found for a device alias 'acpi:LNXSYSTM:'
no matches found for a device alias 'acpi:LNXPWRBN:'
no matches found for a device alias 'acpi:PNP0C0C:'
no matches found for a device alias 'pci:v00001002d000067DFsv00001043sd00000523bc03sc00i00'
no matches found for a device alias 'wmi:ABBC0F6A-8EA1-11D1-00A0-C90629100000'
no matches found for a device alias 'acpi:AMDIF030:AMDIF030:'
no matches found for a device alias 'pci:v00001022d00001451sv00001043sd00008747bc08sc06i00'
no matches found for a device alias 'pci:v00001022d00001466sv00000000sd00000000bc06sc00i00'
no matches found for a device alias 'hid:b0003g0000v0000046Ap00000023'
no matches found for a device alias 'input:b0003v046DpC084e0111-e0,1,2,4,k110,111,112,113,114,115,116,117,118,119,11A,11B,11C,11D,11E,11F,r0,1,6,8,B,C,am4,lsfw'
no matches found for a device alias 'pci:v00001022d00001461sv00000000sd00000000bc06sc00i00'
no matches found for a device alias 'acpi:AMDI0030:AMDI0030:'
no matches found for a device alias 'acpi:PNP0B00:'
no matches found for a device alias 'pci:v00001022d000043B8sv00001B21sd00001062bc01sc06i01'
no matches found for a device alias 'pci:v00001022d000043B3sv00001B21sd00000201bc06sc04i00'
no matches found for a device alias 'pci:v00001022d00001456sv00001043sd00008747bc10sc80i00'
no matches found for a device alias 'pci:v00001022d00001457sv00001043sd000086C7bc04sc03i00'
no matches found for a device alias 'acpi:PNP0100:'
no matches found for a device alias 'pci:v00001022d00001450sv00001043sd00008747bc06sc00i00'
no matches found for a device alias 'pci:v00001022d00001462sv00000000sd00000000bc06sc00i00'
no matches found for a device alias 'platform:microcode'
no matches found for a device alias 'pci:v00001022d00001455sv00001043sd00008747bc13sc00i00'
no matches found for a device alias 'acpi:PNP0200:'
no matches found for a device alias 'usb:v1D6Bp0002d0514dc09dsc00dp01ic09isc00ip00in00'
no matches found for a device alias 'hid:b0003g0001v0000046Dp0000C084'
no matches found for a device alias 'input:b0003v046DpC084e0111-e0,1,2,3,4,14,k71,72,73,74,75,77,79,7A,7B,7C,7D,7E,7F,80,81,82,83,84,85,86,87,88,89,8A,8B,8C,8E,8F,90,96,98,9B,9C,9E,9F,A1,A3,A4,A5,A6,A7,A8,A9,AB,AC,AD,AE,B0,B1,B2,B5,B6,B7,B8,B9,BA,BB,BC,BD,BE,BF,C0,C1,C2,CE,CF,D0,D1,D2,D4,D8,D9,DB,DF,E0,E1,E4,E5,E6,E7,E8,E9,EA,EB,F0,F1,F4,100,161,162,166,16A,16E,172,174,176,177,178,179,17A,17B,17C,17D,17F,180,182,183,185,188,189,18C,18D,18E,18F,190,191,192,193,195,197,198,199,19A,19C,1A0,1A1,1A2,1A3,1A4,1A5,1A6,1A7,1A8,1A9,1AA,1AB,1AC,1AD,1AE,1AF,1B0,1B1,1B7,1BA,240,241,242,243,244,245,246,247,249,250,251,r6,C,a20,m4,lsfw'
no matches found for a device alias 'platform:intel_rapl_msr'
no matches found for a device alias 'platform:serial8250'
no matches found for a device alias 'acpi:PNP0C01:'
no matches found for a device alias 'acpi:PNP0C02:'
no matches found for a device alias 'pci:v00001022d00007901sv00001043sd00008747bc01sc06i01'
no matches found for a device alias 'wmi:466747A0-70EC-11DE-8A39-0800200C9A66'
no matches found for a device alias 'mmc:block'
no matches found for a device alias 'input:b0003v046Ap0023e0111-e0,1,4,11,14,k71,72,73,74,75,77,79,7A,7B,7C,7D,7E,7F,80,81,82,83,84,85,86,87,88,89,8A,8C,8E,96,98,9E,9F,A1,A3,A4,A5,A6,AD,B0,B1,B2,B3,B4,B7,B8,B9,BA,BB,BC,BD,BE,BF,C0,C1,C2,F0,ram4,l0,1,2,sfw'
no matches found for a device alias 'input:b0000v0000p0000e0000-e0,5,kramlsfw6,8,'
no matches found for a device alias 'acpi:PNP0103:'
no matches found for a device alias 'dmi:bvnAmericanMegatrendsInc.:bvr5603:bd10/14/2020:br5.13:svnSystemmanufacturer:pnSystemProductName:pvrSystemVersion:rvnASUSTeKCOMPUTERINC.:rnPRIMEA320M-K:rvrRevX.0x:cvnDefaultstring:ct3:cvrDefaultstring:skuSKU:'
no matches found for a device alias 'acpi:PNP0000:'
no matches found for a device alias 'acpi:PNP0800:'
no matches found for a device alias 'wmi:05901221-D566-11D1-B2F0-00A0C9062910'
no matches found for a device alias 'input:b0019v0000p0000e0000-e0,1,4,14,k71,72,73,8B,94,98,AB,AC,B8,B9,D4,E0,E1,E3,EE,F0,1AF,212,215,216,217,218,219,21A,ram4,lsfw'
no matches found for a device alias 'input:b0000v0000p0000e0000-e0,5,kramlsfw2,'
no matches found for a device alias 'pci:v00001022d0000790Esv00001043sd00008747bc06sc01i00'
no matches found for a device alias 'pci:v00001002d0000AAF0sv00001043sd0000AAF0bc04sc03i00'
no matches found for a device alias 'input:b0000v0000p0000e0000-e0,5,kramlsfw4,'
no matches found for a device alias 'pci:v00001022d00001465sv00000000sd00000000bc06sc00i00'
no matches found for a device alias 'wmi:97845ED0-4E6D-11DE-8A39-0800200C9A66'
no matches found for a device alias 'wmi:B82BB115-43AE-4B35-B79D-BD6416ABC381'
no matches found for a device alias 'usb:v0A12p0001d8891dcE0dsc01dp01icE0isc01ip01in00'
no matches found for a device alias 'platform:sp5100-tco'
no matches found for a device alias 'platform:alarmtimer'
no matches found for a device alias 'platform:efi-framebuffer'
no matches found for a device alias 'platform:efivars'
no matches found for a device alias 'pci:v00001022d00001454sv00001043sd00008747bc06sc04i00'
no matches found for a device alias 'input:b0000v0000p0000e0000-e0,5,kramlsfwD,'
no matches found for a device alias 'wmi:ABBC0F72-8EA1-11D1-00A0-C90629100000'
no matches found for a device alias 'input:b0010v001Fp0001e0100-e0,12,kramls1,2,fw'
no matches found for a device alias 'usb:v1D6Bp0003d0514dc09dsc00dp03ic09isc00ip00in00'
no matches found for a device alias 'pci:v00001022d000043B4sv00001B21sd00003306bc06sc04i00'
no matches found for a device alias 'hdaudio:v10EC0887r00100302a01'
no matches found for a device alias 'input:b0000v0000p0000e0000-e0,5,kramlsfw6,'
no matches found for a device alias 'pci:v00001022d00001460sv00000000sd00000000bc06sc00i00'
no matches found for a device alias 'platform:eeepc-wmi'
no matches found for a device alias 'platform:pcspkr'
no matches found for a device alias 'platform:rtc-efi'
no matches found for a device alias 'acpi:PNP0C14:'
no matches found for a device alias 'pci:v00001022d00001452sv00000000sd00000000bc06sc00i00'
no matches found for a device alias 'hdaudio:v1002AA01r00100700a01'
no matches found for a device alias 'pci:v00001022d0000145Asv00001043sd00008747bc13sc00i00'
no matches found for a device alias 'pci:v00001022d0000790Bsv00001043sd00008747bc0Csc05i00'
no matches found for a device alias 'acpi:PNP0A08:PNP0A03:'
no matches found for a device alias 'acpi:PNP0C0F:'
module 'xen' currently used at the host but was not added to the image
module 'btusb' currently used at the host but was not added to the image
module 'memory_hotplug' currently used at the host but was not added to the image
module 'blk_cgroup' currently used at the host but was not added to the image
module 'secretmem' currently used at the host but was not added to the image
module 'xz_dec' currently used at the host but was not added to the image
module 'cpuidle' currently used at the host but was not added to the image
module 'rtc_cmos' currently used at the host but was not added to the image
module 'dynamic_debug' currently used at the host but was not added to the image
module 'fb_sys_fops' currently used at the host but was not added to the image
module 'sg' currently used at the host but was not added to the image
module 'video' currently used at the host but was not added to the image
module 'vboxnetadp' currently used at the host but was not added to the image
module 'wmi_bmof' currently used at the host but was not added to the image
module 'apparmor' currently used at the host but was not added to the image
module 'snd_hwdep' currently used at the host but was not added to the image
module 'edac_mce_amd' currently used at the host but was not added to the image
module 'snd_hda_intel' currently used at the host but was not added to the image
module 'page_reporting' currently used at the host but was not added to the image
module 'btbcm' currently used at the host but was not added to the image
module 'hid_cherry' currently used at the host but was not added to the image
module 'clocksource' currently used at the host but was not added to the image
module 'printk' currently used at the host but was not added to the image
module 'device_hmem' currently used at the host but was not added to the image
module 'i2c_algo_bit' currently used at the host but was not added to the image
module 'sparse_keymap' currently used at the host but was not added to the image
module 'kernel' currently used at the host but was not added to the image
module 'fb' currently used at the host but was not added to the image
module 'button' currently used at the host but was not added to the image
module 'bnep' currently used at the host but was not added to the image
module 'module' currently used at the host but was not added to the image
module '8250' currently used at the host but was not added to the image
module 'drm_kms_helper' currently used at the host but was not added to the image
module 'pciehp' currently used at the host but was not added to the image
module 'mac_hid' currently used at the host but was not added to the image
module 'intel_rapl_msr' currently used at the host but was not added to the image
module 'keyboard' currently used at the host but was not added to the image
module 'edac_core' currently used at the host but was not added to the image
module 'rpcsec_gss_krb5' currently used at the host but was not added to the image
module 'drm' currently used at the host but was not added to the image
module 'ipv6' currently used at the host but was not added to the image
module 'libata' currently used at the host but was not added to the image
module 'msr' currently used at the host but was not added to the image
module 'netpoll' currently used at the host but was not added to the image
module 'joydev' currently used at the host but was not added to the image
module 'blk_crypto' currently used at the host but was not added to the image
module 'thermal' currently used at the host but was not added to the image
module 'ns' currently used at the host but was not added to the image
module 'rcutree' currently used at the host but was not added to the image
module 'i2c_piix4' currently used at the host but was not added to the image
module 'efi_pstore' currently used at the host but was not added to the image
module 'rfkill' currently used at the host but was not added to the image
module 'x_tables' currently used at the host but was not added to the image
module 'crc_t10dif' currently used at the host but was not added to the image
module 'battery' currently used at the host but was not added to the image
module 'bluetooth' currently used at the host but was not added to the image
module 'firmware_class' currently used at the host but was not added to the image
module 'snd_hda_codec_hdmi' currently used at the host but was not added to the image
module 'pinctrl_amd' currently used at the host but was not added to the image
module 'intel_pmc_core' currently used at the host but was not added to the image
module 'snd_timer' currently used at the host but was not added to the image
module 'gpio_amdpt' currently used at the host but was not added to the image
module 'pcspkr' currently used at the host but was not added to the image
module 'pnp' currently used at the host but was not added to the image
module 'suspend' currently used at the host but was not added to the image
module 'snd_pcm' currently used at the host but was not added to the image
module 'cpufreq' currently used at the host but was not added to the image
module 'ip_tables' currently used at the host but was not added to the image
module 'ttm' currently used at the host but was not added to the image
module 'syscopyarea' currently used at the host but was not added to the image
module 'snd_hda_codec' currently used at the host but was not added to the image
module 'ledtrig_audio' currently used at the host but was not added to the image
module 'gpiolib_acpi' currently used at the host but was not added to the image
module 'nvme' currently used at the host but was not added to the image
module 'cec' currently used at the host but was not added to the image
module 'block' currently used at the host but was not added to the image
module 'btrtl' currently used at the host but was not added to the image
module 'sysrq' currently used at the host but was not added to the image
module 'acpi_cpufreq' currently used at the host but was not added to the image
module 'tcp_cubic' currently used at the host but was not added to the image
module 'sysimgblt' currently used at the host but was not added to the image
module 'nvme_core' currently used at the host but was not added to the image
module 'workqueue' currently used at the host but was not added to the image
module 'soundcore' currently used at the host but was not added to the image
module 'snd_intel_dspcfg' currently used at the host but was not added to the image
module 'hid' currently used at the host but was not added to the image
module 'usbcore' currently used at the host but was not added to the image
module 'page_alloc' currently used at the host but was not added to the image
module 'acpiphp' currently used at the host but was not added to the image
module 'shpchp' currently used at the host but was not added to the image
module 'hwmon_vid' currently used at the host but was not added to the image
module 'random' currently used at the host but was not added to the image
module 'snd_hda_codec_realtek' currently used at the host but was not added to the image
module 'eeepc_wmi' currently used at the host but was not added to the image
module 'vt' currently used at the host but was not added to the image
module 'libahci' currently used at the host but was not added to the image
module 'kfence' currently used at the host but was not added to the image
module 'acpi' currently used at the host but was not added to the image
module 'k10temp' currently used at the host but was not added to the image
module 'asus_wmi' currently used at the host but was not added to the image
module 'irqbypass' currently used at the host but was not added to the image
module 'zram' currently used at the host but was not added to the image
module 'scsi_mod' currently used at the host but was not added to the image
module 'amdgpu' currently used at the host but was not added to the image
module 'sp5100_tco' currently used at the host but was not added to the image
module 'qrtr' currently used at the host but was not added to the image
module 'pci_hotplug' currently used at the host but was not added to the image
module 'wmi' currently used at the host but was not added to the image
module 'snd_intel_sdw_acpi' currently used at the host but was not added to the image
module 'intel_idle' currently used at the host but was not added to the image
module 'snd' currently used at the host but was not added to the image
module 'snd_hda_core' currently used at the host but was not added to the image
module 'snd_hda_codec_generic' currently used at the host but was not added to the image
module 'spurious' currently used at the host but was not added to the image
module 'pcie_aspm' currently used at the host but was not added to the image
module 'slab_common' currently used at the host but was not added to the image
module 'fscrypto' currently used at the host but was not added to the image
module 'gpio_generic' currently used at the host but was not added to the image
module 'rcupdate' currently used at the host but was not added to the image
module 'processor' currently used at the host but was not added to the image
module 'watchdog' currently used at the host but was not added to the image
module 'acpi_call' currently used at the host but was not added to the image
module 'crc16' currently used at the host but was not added to the image
module 'bpf_preload' currently used at the host but was not added to the image
module 'btintel' currently used at the host but was not added to the image
module 'vboxnetflt' currently used at the host but was not added to the image
module 'drm_ttm_helper' currently used at the host but was not added to the image
module 'nmi_backtrace' currently used at the host but was not added to the image
module 'haltpoll' currently used at the host but was not added to the image
module 'kvm' currently used at the host but was not added to the image
module 'intel_rapl_common' currently used at the host but was not added to the image
module 'vboxdrv' currently used at the host but was not added to the image
module 'srcutree' currently used at the host but was not added to the image
module 'mousedev' currently used at the host but was not added to the image
module 'auth_rpcgss' currently used at the host but was not added to the image
module 'zswap' currently used at the host but was not added to the image
module 'agpgart' currently used at the host but was not added to the image
module 'libnvdimm' currently used at the host but was not added to the image
module 'sysfillrect' currently used at the host but was not added to the image
module 'rapl' currently used at the host but was not added to the image
module 'ccp' currently used at the host but was not added to the image
module 'gpu_sched' currently used at the host but was not added to the image
enabling virtual console
detected language - 'de_DE.UTF-8'
/etc/vconsole.conf does not provide FONT settings, skip vconsole font configuration
```

The keyboard is a usual USB keyboard, nothing special like bluetooth. (046a:0023)

**Comment by anatol** [comment] 2021-09-29 17:42
> `modules_force_load: hid_cherry` helped as a workaround.

thank you for this info.

Right now booster uses `kernel/drivers/hid/usbhid/` to check the modules that need to be added to image by default. `hid_cherry` that is located at `kernel/drivers/hid` thus config modification is needed.

I checked mkinitcpio and I see that it checks for `kernel/drivers/hid/hid*` modules. I think booster should lookup modules at `kernel/drivers/hid/` as well.

**Comment by anatol** [comment] 2021-09-29 17:43
@bjo81  Could you please check if this commit https://github.com/anatol/booster/commit/950b1f8c2207690feb84c2ffc36491f038758378 makes your keyboard functional by default without any config modification?

**Comment by bjo81** [comment] 2021-09-29 18:16
Thanks, keyboard works now by default.

**Closed** 2021-10-02 22:30 UTC
